import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

async function exportAbis() {
    const contractNames = ['Minter', 'PhytCards', 'Executor', 'Exchange'];

    const abiDir = join(__dirname, '../src/abi');
    const indexPath = join(__dirname, '../src/index.ts');

    mkdirSync(abiDir, { recursive: true });

    for (const name of contractNames) {
        const artifact = require(`../out/${name}.sol/${name}.json`);
        writeFileSync(
            join(abiDir, `${name}.json`),
            JSON.stringify(artifact.abi, null, 2)
        );
    }

    const indexContent = `// Auto-generated by export-abis.ts
${contractNames.map((name) => `import ${name}Abi from './abi/${name}.json';`).join('\n')}

export { ${contractNames.map((name) => `${name}Abi`).join(', ')} };
`;

    writeFileSync(indexPath, indexContent);
}

exportAbis().catch(console.error);
